services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - pf-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: portfolio_db
      DB_PORT: 5432
      PORT: 3000
    networks:
      - pf-network
    depends_on:
      - db

  db:
    image: postgres:15.10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/portfolio_db.sql:/docker-entrypoint-initdb.d/portfolio_db.sql
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432" # Only expose for debugging/local access
    networks:
      - pf-network

networks:
  pf-network:
    driver: bridge

volumes:
  db_data: