version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - pf-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: portfolio_db
      DB_PORT: 5432
      PORT: 3000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - pf-network
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - pf-network

  db:
    image: postgres:15.10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/portfolio_db.sql:/docker-entrypoint-initdb.d/portfolio_db.sql
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - pf-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pf-network

networks:
  pf-network:
    driver: bridge

volumes:
  db_data:
